
seed: 123

data:
  n_channels: 1
  batch_size: 2
  prep_files: {
                data: ./src/data/prep/prep_mix_2026_02_18_15_01_49_nSetups20_10dB_whiteNoise.hdf5,
                meta: ./src/data/prep/prep_mix_meta_2026_02_18_15_01_49_nSetups20_10dB_whiteNoise.json,
              }
  dry_target: True
  snr_range: []
  meta_frame_length: 160000
  stft_length_samples: 512
  stft_shift_samples: 256
  n_workers: 10

network:
  n_time_steps: 624
  n_freqs: 257
  n_channels: 1
  n_lstm_hidden1: 256
  n_lstm_hidden2: 128
  bidirectional: True
  output_type: 'CRM'
  output_activation: 'tanh'
  append_freq_idx: False
  permute_freqs: True
  dropout: 0
  narrow_band: True

experiment:
  learning_rate: 0.001
  weight_decay: 0
  loss_alpha: 10
  cirm_comp_K: 1
  cirm_comp_C: 1
  reference_channel: 0

training:
  max_epochs: 50
  gradient_clip_val: 0
  gradient_clip_algorithm: value
  strategy: ddp
  accelerator: gpu
  devices: 1


logging:
  tb_log_dir: "./logs/tb_logs"
  ckpt_dir: "./logs/ckpts"