
seed: 123

data:
  n_channels: 4
  batch_size: 2
  prep_files: {
                data: ./src/data/prep/prep_mix_2025_12_02_15_33_55_nSetups20_15dB_400ms.hdf5,
                meta: ./src/data/prep/prep_mix_meta_2025_12_02_15_33_55_nSetups20_15dB_400ms.json,
              }
  dry_target: True
  snr_range: []
  meta_frame_length: 48000
  stft_length_samples: 512
  stft_shift_samples: 256
  n_workers: 10

network:
  n_channels: 4
  n_lstm_hidden1: 256
  n_lstm_hidden2: 128
  bidirectional: True
  freq_first: True
  output_type: 'CRM'
  output_activation: 'tanh'
  append_freq_idx: False
  permute_freqs: False
  dropout: 0

experiment:
  learning_rate: 0.001
  weight_decay: 0
  loss_alpha: 10
  cirm_comp_K: 1
  cirm_comp_C: 1
  reference_channel: 0

training:
  max_epochs: 2
  gradient_clip_val: 0
  gradient_clip_algorithm: value
  strategy: ddp
  # todo: check why gpu does not work
  accelerator: cpu
  devices: 1


logging:
  tb_log_dir: "./logs/tb_logs"
  ckpt_dir: "./logs/ckpts"